kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-deleter-lister
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-list-pods-global
subjects:
  - kind: ServiceAccount
    name: default
    namespace: workloads
roleRef:
  kind: ClusterRole
  name: pod-deleter-lister
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-chaos-monkey
  name: pod-chaos-monkey
  namespace: workloads
spec:
  containers:
    - name: pod-chaos-monkey
      image: pod-chaos-monkey:latest
      args:
        - workloads
        - '--selector=app=nginx,env=dev'
      imagePullPolicy: Never
