apiVersion: v1
kind: Namespace
metadata:
  name: workloads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: workloads
spec:
  selector:
    matchLabels:
      app: nginx
      env: dev
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.1
          ports:
            - containerPort: 80
---